version: '3'

services:
  api:
    build:
      context: ./images
      dockerfile: ApiDevDockerfile
    # :cached ONLY on MacOS.  Remove otherwise.
    volumes:
      - ./api:/usr/src/api:cached
    # NEW
    ports:
      # machine:container
      - 3001:3000
    command: yarn start
    env_file:
      - ./env/dev.env

  devdb:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # keeps db data local and easy to reset
    volumes:
      - ./devdb:/var/lib/mysql
      # conf.d is a folder, and it reads whatever `.cnf` files are in there
      - ./env:/etc/mysql/conf.d
    ports:
      - 3306:3306
    env_file:
      - ./env/dev.env